name: simple_pdf_generator
description: A lightweight Flutter package to generate PDFs from structured data.
version: 0.2.0

homepage: https://github.com/MohsinP07/simple_pdf_generator
repository: https://github.com/MohsinP07/simple_pdf_generator
issue_tracker: https://github.com/MohsinP07/simple_pdf_generator/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.7.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/fonts/NotoSans-Variable.ttf
    - assets/fonts/OFL.txt
    - assets/fonts/Roboto-Variable.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Lato-Regular.ttf
    - assets/fonts/Roboto-LICENSE.txt
    - assets/fonts/Poppins-LICENSE.txt
    - assets/fonts/Lato-LICENSE.txt
